version: '3.3'
services:
  soketi:
    container_name: 'soketi'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:0.17-16-alpine'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    env_file:
      - .env
    environment:
      - DEBUG='${DEBUG:-1}'
      - PUSHER_HOST='${PUSHER_HOST:-127.0.0.1}'
      - PUSHER_PORT= '${PUSHER_PORT:-6001}'
      - PUSHER_SCHEME='${PUSHER_SCHEME:-https}' # or https
      - METRICS_SERVER_PORT=${METRICS_SERVER_PORT-9601}
      - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES-false}
    networks:
      - soketi_network

networks:
  soketi_network:
    driver: bridge
